# Generated by Django 2.1.4 on 2019-01-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-updated',)},
        ),
    ]
