# Generated by Django 2.1.4 on 2018-12-17 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20181211_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_questions', to='question.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(default=''),
        ),
    ]
